version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "9003:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build: .
        volumes:
            - ./code:/code
        networks:
            - code-network
        user: www-data


networks:
    code-network:
        driver: bridge
